### ISSUE TITLE
Can't install github-color in package.json.

### ISSUE THREAD

**Issue by vanloc0301** [trungdq88/github-explorer#4]
I have problem when to installing all package with command:

`npm install`

I throws exception like: 

> Failed at the github-colors@2.2.5 install script './build/main'.

OS: Windows 7 seem not working with many packages relate to graphics.

**Comment by trungdq88** [comment]
Can you post the full log?

**Comment by vanloc0301** [comment]
In npm-debug.log:

```
Error: github-colors@2.2.5 install: `./build/main`
EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
emitTwo (events.js:106:13)
EventEmitter.emit (events.js:191:7)
ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
emitTwo (events.js:106:13)
ChildProcess.emit (events.js:191:7)
maybeClose (internal/child_process.js:852:16)
Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
pkgid github-colors@2.2.5
cwd E:\javascript\github-explorer
node v6.3.0
npm  v3.10.3
code ELIFECYCLE
github-colors@2.2.5 install: `./build/main`
Failed at the github-colors@2.2.5 install script './build/main'.
Make sure you have the latest version of node.js and npm installed.
If you do, this is most likely a problem with the github-colors package,
not with npm itself.
Tell the author that this fails on your system:
    ./build/main
You can get information on how to open an issue for this project with:
    npm bugs github-colors
Or if that isn't available, you can get their info via:
    npm owner ls github-colors
```

With lastest Node.js version.

**Comment by trungdq88** [comment]
I don't have a Windows 7 so I cannot reproduce the problem, but I have filed [an issue here on the github-colors repo](https://github.com/IonicaBizau/github-colors/issues/12) to see if the package's author have any idea about this. Can you keep track on that issue and provide more information if needed?

In case the guy can't fix it, I can consider to remove that package and use something else for the colors instead.

**Comment by vanloc0301** [comment]
Thanks,  @trungdq88 . I will consider this issues.
